#!/usr/bin/env bash
# This scrip automate the configuration of an Nginx
# server to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
