#!/usr/bin/env bash
# This script automates the configuration of
# an Nginx server to listen on port 80.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
